/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Surface system
        "surface":                  "#0b1326",
        "surface-dim":              "#0b1326",
        "surface-bright":           "#31394d",
        "surface-container-lowest": "#060e20",
        "surface-container-low":    "#131b2e",
        "surface-container":        "#171f33",
        "surface-container-high":   "#222a3d",
        "surface-container-highest":"#2d3449",
        "surface-variant":          "#2d3449",
        "surface-tint":             "#c0c1ff",
        "background":               "#0b1326",
        // On-surface
        "on-surface":               "#dae2fd",
        "on-surface-variant":       "#c7c4d7",
        "on-background":            "#dae2fd",
        "inverse-surface":          "#dae2fd",
        "inverse-on-surface":       "#283044",
        // Primary
        "primary":                  "#c0c1ff",
        "primary-fixed":            "#e1e0ff",
        "primary-fixed-dim":        "#c0c1ff",
        "primary-container":        "#8083ff",
        "on-primary":               "#1000a9",
        "on-primary-container":     "#0d0096",
        "on-primary-fixed":         "#07006c",
        "on-primary-fixed-variant": "#2f2ebe",
        "inverse-primary":          "#494bd6",
        // Secondary
        "secondary":                "#c4c7c9",
        "secondary-fixed":          "#e0e3e5",
        "secondary-fixed-dim":      "#c4c7c9",
        "secondary-container":      "#464a4b",
        "on-secondary":             "#2d3133",
        "on-secondary-container":   "#b6b9bb",
        "on-secondary-fixed":       "#191c1e",
        "on-secondary-fixed-variant":"#444749",
        // Tertiary (green – positive sentiment)
        "tertiary":                 "#4edea3",
        "tertiary-fixed":           "#6ffbbe",
        "tertiary-fixed-dim":       "#4edea3",
        "tertiary-container":       "#00885d",
        "on-tertiary":              "#003824",
        "on-tertiary-container":    "#000703",
        "on-tertiary-fixed":        "#002113",
        "on-tertiary-fixed-variant":"#005236",
        // Error (red – negative sentiment)
        "error":                    "#ffb4ab",
        "error-container":          "#93000a",
        "on-error":                 "#690005",
        "on-error-container":       "#ffdad6",
        // Outline
        "outline":                  "#908fa0",
        "outline-variant":          "#464554",
        // Sentiment aliases
        "positive":                 "#4edea3",
        "negative":                 "#ffb4ab",
        "warning":                  "#f5c542",
      },
      fontFamily: {
        sans:  ["Geist", "ui-sans-serif", "system-ui", "sans-serif"],
        mono:  ["JetBrains Mono", "ui-monospace", "monospace"],
        geist: ["Geist", "sans-serif"],
      },
      fontSize: {
        "display":    ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "headline-lg":["32px", { lineHeight: "40px", letterSpacing: "-0.02em",  fontWeight: "600" }],
        "headline-md":["24px", { lineHeight: "32px", letterSpacing: "-0.01em",  fontWeight: "600" }],
        "headline-sm":["20px", { lineHeight: "28px",                             fontWeight: "500" }],
        "title-lg":   ["16px", { lineHeight: "24px",                             fontWeight: "600" }],
        "title-md":   ["14px", { lineHeight: "20px",                             fontWeight: "600" }],
        "body-lg":    ["16px", { lineHeight: "24px",                             fontWeight: "400" }],
        "body-md":    ["14px", { lineHeight: "20px",                             fontWeight: "400" }],
        "body-sm":    ["12px", { lineHeight: "16px",                             fontWeight: "400" }],
        "label-lg":   ["14px", { lineHeight: "20px", letterSpacing: "0.02em",   fontWeight: "500" }],
        "label-md":   ["12px", { lineHeight: "16px", letterSpacing: "0.05em",   fontWeight: "500" }],
        "label-sm":   ["11px", { lineHeight: "16px", letterSpacing: "0.06em",   fontWeight: "500" }],
      },
      spacing: {
        "xs":  "4px",
        "sm":  "8px",
        "md":  "12px",
        "lg":  "16px",
        "xl":  "24px",
        "2xl": "32px",
        "3xl": "48px",
      },
      borderRadius: {
        "sm":   "4px",
        "DEFAULT": "6px",
        "md":   "8px",
        "lg":   "12px",
        "xl":   "16px",
        "2xl":  "20px",
        "full": "9999px",
      },
      boxShadow: {
        "card":     "0 1px 3px rgba(0,0,0,0.4), 0 1px 2px rgba(0,0,0,0.3)",
        "elevated": "0 4px 16px rgba(0,0,0,0.5)",
        "glow-primary": "0 0 20px rgba(192,193,255,0.15)",
        "glow-positive": "0 0 12px rgba(78,222,163,0.2)",
        "glow-negative": "0 0 12px rgba(255,180,171,0.2)",
      },
      backdropBlur: {
        "glass": "12px",
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in":    "fadeIn 0.2s ease-out",
        "slide-in":   "slideIn 0.25s ease-out",
      },
      keyframes: {
        fadeIn:  { from: { opacity: "0" },                         to: { opacity: "1" } },
        slideIn: { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
      },
    },
  },
  plugins: [],
}
